### ISSUE TITLE
LNK2019	unresolved external symbol "int __cdecl area(struct Rectangle const &)" (?area@@YAHAEBURectangle@@@Z::<!BasicPlane.Figures>) referenced in function main

### ISSUE THREAD

**Issue by netcan** [MicrosoftDocs/cpp-docs#3615]
hello, I tested the code in visual studio 2022 current, compiled will report `[LNK2019] unresolved external symbol "int __cdecl area(struct Rectangle const &)" (?area@@YAHAEBURectangle@@@Z::<!BasicPlane.Figures>) referenced in function main`, but only `height` and `width` function works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01648994-5c73-a88d-bc78-dbab40d834d7
* Version Independent ID: 01648994-5c73-a88d-bc78-dbab40d834d7
* Content: [Named modules tutorial in C++](https://docs.microsoft.com/en-us/cpp/cpp/tutorial-named-modules-cpp?view=msvc-170)
* Content Source: [docs/cpp/tutorial-named-modules-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/tutorial-named-modules-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@netcan 

Thanks for the report, and your patience. The code didn't link for me in 17.0 either, but then I noticed this line in the tutorial:

> For this tutorial, you'll need Visual Studio 2022 17.1.0 or later.

I verified that the tutorial does in fact work in the 17.1 preview builds. We don't usually publish tutorials until the compiler they require is released, so someone may have poked the publish button on this article too soon. Possibly me. Apologies for the misuse of your time.

I'm closing the issue as 17.1 previews are available now and the 17.1 release is coming shortly, probably within a couple of weeks.
