### ISSUE TITLE
Page should suggest next steps

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/cpp-docs#3927]
I encounter this C1252 issue frequently when trying to get Static Driver Verifier (SDV) working in VS2019 16.11.15. The GUI is useless and just tells the user to make sure the project can build correctly, but when the /debug option is used at the command line the error can be found in smvcl.log as _"c1xx : fatal error C1252: Circular or missing dependency between plugins: 'PREfast Drivers Plugin' requires GUID '{EB170136-3433-4C16-AE1D-8998BA5CAB16}'."_

This typically will lead to a web search, often to finding the C1252 page, which kind of dead ends with telling users it's an internal error.

Which it _is,_ but it'd be nice to provide users with _some_ path forward, even if the next step is a link to submitting a bug report to Microsoft. Supposedly, [it can sometimes help to turn off Enable Code Analysis on Build](https://www.osr.com/blog/2020/11/16/making-sdv-work-vs-2019-wdk-2004/), but that does not always succeed; still, that might also be worth a mention. Any other suggestions to help driver developers past this would be greatly appreciated here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d6b5e9-add7-3d62-a064-1dc3ecbadc55
* Version Independent ID: d520a35d-81d0-3fd4-02c8-0066f70bb351
* Content: [C1252](https://docs.microsoft.com/en-us/cpp/code-quality/c1252?view=msvc-170)
* Content Source: [docs/code-quality/c1252.md](https://github.com/Microsoft/cpp-docs/blob/main/docs/code-quality/c1252.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@druske 
Thanks for the report. I'm sorry there isn't a better solution available for the problem. I've written up what little workaround information is known and added it to the article.
