### ISSUE TITLE
To create a DLL project in Visual Studio 2019 fails after first create DLL with compile error

### ISSUE THREAD

**Issue by GuidoSE** [MicrosoftDocs/cpp-docs#4272]
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\sdkddkver.h(276,1): fatal error C1189: #error:  WINVER setting conflicts with _WIN32_WINNT setting

I started to create the DLL in VS2019 (16.10.3) as described with prerequisites "Desktop development with C++",   created header and cpp copied respective code hit compile and get above error. This page need updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08c574a2-cef0-ab13-7375-55851f966ef6
* Version Independent ID: fe3421c7-e9f4-4986-589f-fadaedce583e
* Content: [Walkthrough: Create and use your own Dynamic Link Library (C++)](https://learn.microsoft.com/en-us/cpp/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp?view=msvc-170)
* Content Source: [docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/build/walkthrough-creating-and-using-a-dynamic-link-library-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@GuidoSE 
I'm sorry you're having trouble. The error you describe is unexpected, and I can't reproduce it with VS2019. You shouldn't need to set `WINVER` or `_WIN32_WINNT` at all. Things to try: Verify that you're using the correct template, and try to build the DLL created by the template before you make any changes to it. It should build successfully. If it doesn't, there may be a problem with your Visual Studio installation. Once it builds successfully, then try the remaining steps in the walkthrough to create the DLL. If you continue to have trouble, then I recommend getting help from [Microsoft Learn Q&A](https://learn.microsoft.com/en-us/answers/topics/c%2B%2B.html). Since this appears to be a support issue rather than a problem with the documentation, I'm closing it. Best of luck with your code.

**Comment by GuidoSE** [comment]
Hi Colin,

Thank you for your reply. I think a re-install of VS2019 Pro is my next option.

I tried the same example on VS2019 Community edition, home pc, the example worked however I did need to correct the name of the PREPROSSOR value MATHLIBRARY as it was miss-spelt in this version of VS2019 when first compiling the project. After correcting the value it work. So agree, probably code related bugs/installation issue,

Kind regards

Guido



Internal

**Comment by GuidoSE** [comment]
Hi,

Investigation found the following:


  1.  VS2019 and Windows 10 SDK 10.0.19041.0 are not incompatible, you get the following compilation error with this project (any project):

1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\sdkddkver.h(276,1): fatal error C1189: #error:  WINVER setting conflicts with _WIN32_WINNT setting


  1.  However VS2019 does work with Windows 10 SDK 10.0.18362.0, no problem compiling projects.
  2.  VS2022 and Windows 10 SDK 10.0.19041.0 do work together and  this project will compile. Finding this out shouts poor testing of releases, either the SDK or VS or both! Surely Microsoft could simply automate a smoke test with this project to evaluate a successful compile?

Kind regards

Guido Le Lorrain




Internal
From: Guido Le Lorrain
Sent: 09 November 2022 09:39
To: MicrosoftDocs/cpp-docs ***@***.***>
Subject: RE: [MicrosoftDocs/cpp-docs] To create a DLL project in Visual Studio 2019 fails after first create DLL with compile error (Issue #4272)

Hi Colin,

Thank you for your reply. I think a re-install of VS2019 Pro is my next option.

I tried the same example on VS2019 Community edition, home pc, the example worked however I did need to correct the name of the PREPROSSOR value MATHLIBRARY as it was miss-spelt in this version of VS2019 when first compiling the project. After correcting the value it work. So agree, probably code related bugs/installation issue,

Kind regards

Guido



Internal

**Comment by corob-msft** [comment]
@GuidoSE 

Good work finding a repro case on your system. The various combinations of VS and Windows SDK are in fact tested continuously with each other, and we'd fix issues if we found any. I'm inclined to think the problem is local to your machine, since I have no trouble building the default DLL project in Visual Studio 2019 version 16.11.21 (the latest) with Windows SDK 10.0.19041.0 (set in the Project Properties dialog under **Configuration Properties** > **General** > **Windows SDK Version**).

An earlier version of Visual Studio had a typo in the DLL template that would create the project-specific preprocessor macro in mixed case, rather than all upper case. However, it's fixed in the current version of Visual Studio 2019. I'd recommend using the latest 2019 version with all its bug and security fixes, even if you don't want to move to Visual Studio 2022. You're probably prompted to update it every time you launch Visual Studio.
